version: 18.06-{build}
image:
- Visual Studio 2017
- Visual Studio 2015
skip_tags: true
build_script:
- cmd: >-
    7-zip-build.bat
test: off
skip_commits:
  files:
    - 'LICENSE'
    - '*.md'
    - '.gitingore'